<?php

namespace Pyz\Zed\ProductManagement\Communication\Controller\Index;

class IndexController extends \Spryker\Zed\ProductManagement\Communication\Controller\IndexController
{
//Pyz\Zed\ProductManagement\Communication\Controller\Index\IndexController
    public function indexAction()
    {
        dd('hhh');
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function tableAction()
    {
        return parent::tableAction(); // TODO: Change the autogenerated stub
    }

    protected function executeProductAbstractListActionViewDataExpanderPlugins(array $viewData): array
    {
        dd('exe');
        return parent::executeProductAbstractListActionViewDataExpanderPlugins($viewData); // TODO: Change the autogenerated stub
    }
}
